/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import control.ControlAvion;
import control.Procesos;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import modelo.Bulto;
/**
 *
 * @author Anderson
 */
public class VistaRecepcion extends javax.swing.JFrame {
    ControlAvion objAvion = new ControlAvion();
    Procesos objProcesos = new Procesos();
    /**
     * Creates new form VistaRecepcion
     */
    public VistaRecepcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPesoBulto = new javax.swing.JLabel();
        txtPesoBulto = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInformacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPesoBulto.setText("Peso Bulto:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        tblInformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Peso", "Valor COP", "Valor USD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInformacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFinalizar)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPesoBulto)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesoBulto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesoBulto)
                    .addComponent(txtPesoBulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnFinalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        double capturarPeso;
        double precioEnCOP;
        double precioEnUSD;
        Object object[] = null;
        DefaultTableModel modelo;
        capturarPeso = Double.parseDouble(txtPesoBulto.getText());
        
        if (objAvion.validarAgregar(capturarPeso)) {
            precioEnCOP = objProcesos.calcularPrecioCop(capturarPeso);
            precioEnUSD = objProcesos.convertirADolar(precioEnCOP);
            objAvion.agregarBulto(capturarPeso, precioEnCOP, precioEnUSD);
            modelo = (DefaultTableModel) tblInformacion.getModel();
            modelo.addRow(object);
        } else {
            JOptionPane.showMessageDialog(null, "Bulto supera el peso maximo");
        }
        
        //mostrar bultos en tabla
        for (int i = 0; i < objAvion.objAvion.getBultos().size(); i++) {
            Bulto objBulto = this.objAvion.objAvion.getBultos().get(i);
            tblInformacion.setValueAt(objBulto.getPeso(), i, 0);
            tblInformacion.setValueAt(objBulto.getPrecioEnCop(), i, 1);
            tblInformacion.setValueAt(objBulto.getPrecioEnDolar(), i, 2);
        }
        txtPesoBulto.setText(null);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        if (this.objAvion.objAvion.getContador()>=15) {
            this.setVisible(false);
            double pesoCarga = this.objAvion.objAvion.getPesoAcumulado();
            int numeroDeBultos = this.objAvion.objAvion.getContador();
            double masPesado = this.objProcesos.masPesado(this.objAvion.objAvion.getBultos());
            double masLiviano = this.objProcesos.menosPesado(this.objAvion.objAvion.getBultos());
            double promedio = this.objProcesos.calcularPromedio(numeroDeBultos, pesoCarga);
            double precioEnCOP = this.objProcesos.valorTotalCop(this.objAvion.objAvion.getBultos());
            double precioEnUSD = this.objProcesos.valorTotalUsd(this.objAvion.objAvion.getBultos());
            
            VistaResultado objVResultado = new VistaResultado();
            objVResultado.tblResultado.setValueAt(numeroDeBultos, 0, 0);
            objVResultado.tblResultado.setValueAt(masPesado, 0, 1);
            objVResultado.tblResultado.setValueAt(masLiviano, 0, 2);
            objVResultado.tblResultado.setValueAt(promedio, 0, 3);
            objVResultado.tblResultado.setValueAt(precioEnCOP, 0, 4);
            objVResultado.tblResultado.setValueAt(precioEnUSD, 0, 5);
            objVResultado.setVisible(true);
            
        }else{
           JOptionPane.showMessageDialog(null, "Aún no alcanza el numero de bultos minimos (15)");
        }
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRecepcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesoBulto;
    private javax.swing.JTable tblInformacion;
    private javax.swing.JTextField txtPesoBulto;
    // End of variables declaration//GEN-END:variables
}
